# routes.yml
_helloRoute:
    path:       /hello/{name}
    defaults:   { _controller: "dac\\silex\\controllers\\HelloController::doGet"}
    methods:    GET


_phpSilexOnlyRoute:
    path:       /phpSilexOnly/{name}
    defaults:   { _controller: "dac\\silex\\controllers\\LinksController::doGet"}
    methods:    GET
    host:       phpsilex.local

_silexSiteOnlyRoute:
    path:       /silexSite/{name}
    defaults:   { _controller: "dac\\silex\\controllers\\LinksController::doGet"}
    methods:    GET
    host:       silexsite.local
